---

- name: Install X virtual framebuffer
  yum:
    name: xorg-x11-server-Xvfb
    state: present

- name: Install X virtual framebuffe init script
  template:
    src: "init-xvfb.j2"
    dest: /etc/init.d/xvfb
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"
  tags: [configuration, xvfb, xvfb-install]

- name: Install systemd unit file (for systemd systems)
  template:
    src: "xvfb-unit.j2"
    dest: /etc/systemd/system/xvfb.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'"
  tags: [configuration, xvfb, xvfb-install]

# - name: Register systemd service status (for systemd systems)
#   shell: 'systemctl status xvfb | grep "active (running)"'
#   when: "ansible_service_mgr == 'systemd'"
#   register: xvfb_running
#   ignore_errors: yes
#   changed_when: false

# - name: Ensure xvfb is running
#   service: name=xvfb state=started enabled=yes
#   tags: [configuration, xvfb, xvfb-run]
#   when: xvfb_running.failed is defined and xvfb_running.failed == true
