---

vagrant_box: ortiz/mediacommons
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_gui: false
vagrant_machine_name: mediacommons
vagrant_hostname: mediacommons.local
vagrant_host_protocol: http

vagrant_ip: 192.168.88.88

vagrant_synced_folders:
  - local_path: .
    destination: "/var/www/sites/{{ vagrant_machine_name }}"
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1

# Ensure vagrant plugins are installed.
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater

# Minimum required versions.
drupalvm_vagrant_version_min: '1.8.6'
drupalvm_ansible_version_min: '2.4'

# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false

drupalvm_webserver: apache
drupal_db_backend: mysql
drupal_core_path: "/var/www/sites/{{ vagrant_machine_name }}/builds"
drupal_core_owner: "{{ drupalvm_user }}"
drupal_domain: "{{ vagrant_hostname }}"

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    aliases: 
      - { files: "{{ drupal_core_path }}/alt-ac/drupal/sites/default/files", base: "/alt-ac", directory: "{{ drupal_core_path }}/alt-ac/drupal" }
      - { files: "{{ drupal_core_path }}/imr/drupal/sites/default/files", base: "/imr", directory: "{{ drupal_core_path }}/imr/drupal" }
      - { files: "{{ drupal_core_path }}/fieldguide/drupal/sites/default/files", base: "/fieldguide", directory: "{{ drupal_core_path }}/fieldguide/drupal" }
      - { files: "{{ drupal_core_path }}/intransition/drupal/sites/default/files", base: "/intransition", directory: "{{ drupal_core_path }}/intransition/drupal" }
      - { files: "{{ drupal_core_path }}/tne/drupal/sites/default/files", base: "/tne", directory: "{{ drupal_core_path }}/tne/drupal" }
      - { files: "{{ drupal_core_path }}/mediacommons/drupal/sites/default/files", base: "/", directory: "{{ drupal_core_path }}/mediacommons/drupal/" }
    proxy_pass:
      - { local: "/alt-ac/sites/default/files/", proxy: "http://mediacommons.org/alt-ac/sites/default/files/" }
      - { local: "/fieldguide/sites/default/files/", proxy: "http://mediacommons.org/fieldguide/sites/default/files/" }
      - { local: "/imr/sites/default/files/", proxy: "http://mediacommons.org/imr/sites/default/files/" }
      - { local: "/intransition/sites/default/files/", proxy: "http://mediacommons.org/intransition/sites/default/files/" }
      - { local: "/sites/default/files/", proxy: "http://mediacommons.org/sites/default/files/" }
      - { local: "/tne/sites/default/files/", proxy: "http://mediacommons.org/tne/sites/default/files/" }
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_packages_state: latest
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - headers.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  - proxy_http.load

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - mailhog
  - solr
  - upload-progress
  - java
  - ruby

extra_packages: []

firewall_enabled: true
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1, 7.2.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.2"
php_install_recommends: no
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

# Run specified scripts before or after VM is provisioned. Use {{ playbook_dir }}
# to reference the provisioning/ folder in Drupal VM or {{ config_dir }} to
# reference the directory where your `config.yml` is.
pre_provision_scripts: []
 
post_provision_scripts: []

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300

adminer_install_filename: index.php

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ drupalvm_user }}"
ruby_install_gems: []

# Solr Configuration (if enabled above).
solr_version: "5.5.5"
solr_xms: "64M"
solr_xmx: "128M"

# Other configuration.
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts  
hostname_configure: true
hostname_fqdn: "{{ vagrant_hostname }}"
ssh_home: "{{ drupal_core_path }}"
