---
dependencies: []

galaxy_info:
  author: dismorfo
  description: Node.js installation for CentOS 7
  company: "New York University"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
    - web
    - javascript
    - js
    - nodejs

