---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - ../config.yml

  pre_tasks:                                                                                                                                                                                                      
    - include_tasks: tasks/config.yml
      tags: ['always']

    - include_tasks: tasks/backwards-compatibility.yml
      tags: ['always']

    - include_tasks: "tasks/init-{{ ansible_os_family }}.yml"

    - name: Run configured pre-provision shell scripts.
      script: "{{ item }}"
      with_items: "{{ pre_provision_scripts|default([]) }}"

    - name: Run configured pre-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ pre_provision_tasks_dir|default(omit) }}"     

    - import_tasks: tasks/php.yml

  roles:
    - { role: drupalvm.hostname }
    - { role: geerlingguy.firewall }
    - { role: geerlingguy.git }
    - { role: geerlingguy.postfix }
    - { role: geerlingguy.apache, tags: ['webserver'] }
    - { role: geerlingguy.apache-php-fpm, tags: ['webserver'] }
    - { role: geerlingguy.php-versions, when: php_version != '', tags: ['php', 'xdebug', 'database'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.mysql, tags: ['database'] }
    - { role: geerlingguy.php-mysql, tags: ['php', 'database'] }
    - { role: dismorfo.nodejs }
    - { role: dismorfo.xvfb }
    - { role: dismorfo.nightwatch }
    - { role: dismorfo.chromium }   
    - { role: geerlingguy.memcached }
    - { role: geerlingguy.php-memcached, tags: ['php'] }

    - role: thom8.php-upload-progress
      workspace: "/root/php{{ php_version }}"
      tags: ['php']

    - { role: geerlingguy.adminer, tags: ['database'] }
    - { role: geerlingguy.pimpmylog }
    - { role: geerlingguy.daemonize }
    - { role: geerlingguy.mailhog }
    - { role: geerlingguy.ruby }
    - { role: geerlingguy.java }
    - { role: geerlingguy.solr }
    - { role: dismorfo.home }
    - { role: drupalvm.www, tags: ['webserver'] }

  tasks:
    - import_tasks: tasks/sshd.yml
    - import_tasks: tasks/extras.yml

    - include_tasks: tasks/dashboard.yml
      when: dashboard_install_dir is defined and dashboard_install_dir != ''
      tags: ['webserver', 'database', 'php']

    - name: Run configured post-provision shell scripts.
      script: "{{ item }}"
      with_items: "{{ post_provision_scripts|default([]) }}"

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks_dir|default(omit) }}"
