---

- name: Install MediaCommons VM aliases
  template:
    src: "bash_aliases.j2"
    dest: /home/{{ vagrant_user }}/.bash_aliases
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    mode: 0755

- name: Install MediaCommons VM Bash functions
  template:
    src: "bash_functions.j2"
    dest: /home/{{ vagrant_user }}/.bash_functions
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    mode: 0755

- name: Install MediaCommons VM .my.cnf
  template:
    src: "my.cnf.j2"
    dest: /home/{{ vagrant_user }}/.my.cnf
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    mode: 0755

- name: Make sure .bashrc reads .bash_aliases
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "bash_aliases"
    line: "if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi;"
  become: no

- name: Make sure .bashrc reads .bash_functions
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "bash_functions"
    line: "if [ -f ~/.bash_functions ]; then . ~/.bash_functions; fi;"
  become: no

- name: Set PROJECT in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "PROJECT"
    line: "export PROJECT={{ vagrant_machine_name }}"
  become: no

- name: Set APP_DIR in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "APP_DIR"
    line: "export APP_DIR=/vagrant"
  become: no
 
- name: Set DRUSH in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "DRUSH"
    line: "export DRUSH=/vagrant/source/mediacommons/bin/drush-6.7.0/drush"
  become: no

- name: Set HOST in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "HOST"
    line: "export HOST={{ vagrant_hostname }}"
  become: no

- name: Set PROTOCOL in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "PROTOCOL"
    line: "export PROTOCOL={{ vagrant_host_protocol }}"
  become: no

- name: Set BUILD_PATH in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "BUILD_PATH"
    line: "export BUILD_PATH=/var/www/sites/{{ vagrant_machine_name }}/builds"
  become: no

- name: Set SOLR_CORE in .bashrc
  lineinfile:
    dest: "/home/{{ vagrant_user }}/.bashrc"
    state: present
    create: yes
    regexp: "SOLR_CORE"
    line: "export SOLR_CORE={{ vagrant_host_protocol }}://{{ vagrant_hostname }}:8983/solr/{{ vagrant_machine_name }}"
  become: no

- name: Copy init file to temporary directory
  template:
    src: "init.sh.j2"
    dest: /tmp/init.sh
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Init MediaCommons project
  shell: "/tmp/init.sh"
  become: yes
  become_user: vagrant

- name: Make sure default directory exists
  file:
    path: "{{ item.path }}"
    mode: 0775
    recurse: yes
  with_items:
    - { path: '/vagrant/builds/alt-ac/drupal/sites/default' }
    - { path: '/vagrant/builds/fieldguide/drupal/sites/default' }
    - { path: '/vagrant/builds/imr/drupal/sites/default' }
    - { path: '/vagrant/builds/intransition/drupal/sites/default' }
    - { path: '/vagrant/builds/mediacommons/drupal/sites/default' }
    - { path: '/vagrant/builds/tne/drupal/sites/default' }
    
- name: Configure MediaCommons' sites settings.php.
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'alt-ac.j2', dest: '/vagrant/builds/alt-ac/drupal/sites/default/settings.php' }
    - { src: 'fieldguide.j2', dest: '/vagrant/builds/fieldguide/drupal/sites/default/settings.php' }
    - { src: 'imr.j2', dest: '/vagrant/builds/imr/drupal/sites/default/settings.php' }
    - { src: 'intransition.j2', dest: '/vagrant/builds/intransition/drupal/sites/default/settings.php' }
    - { src: 'mediacommons.j2', dest: '/vagrant/builds/mediacommons/drupal/sites/default/settings.php' }
    - { src: 'tne.j2', dest: '/vagrant/builds/tne/drupal/sites/default/settings.php' }
  