---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define extra php_packages.
  set_fact:
    php_packages: "{{ php_packages | list + php_packages_extra | list }}"
  when: php_packages_extra is defined

- name: Define php_webserver_daemon.
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined

- name: Define php_conf_paths.
  set_fact:
    php_conf_paths: "{{ __php_conf_paths }}"
  when: php_conf_paths is not defined

- name: Define php_extension_conf_paths.
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined

- name: Define php_apc_conf_filename.
  set_fact:
    php_apc_conf_filename: "{{ __php_apc_conf_filename }}"
  when: php_apc_conf_filename is not defined

- name: Define php_opcache_conf_filename (Ubuntu 16.04).
  set_fact:
    php_opcache_conf_filename: "10-opcache.ini"
  when: php_opcache_conf_filename is not defined and ansible_distribution_version == "16.04"

- name: Define php_opcache_conf_filename.
  set_fact:
    php_opcache_conf_filename: "{{ __php_opcache_conf_filename }}"
  when: php_opcache_conf_filename is not defined

- name: Define php_fpm_conf_path.
  set_fact:
    php_fpm_conf_path: "{{ __php_fpm_conf_path }}"
  when: php_fpm_conf_path is not defined

- name: Install Extra Packages for Enterprise Linux (EPEL)
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Check if RedHat remi-release-7 is installed
  command: rpm -q remi-release-7.5-2.el7.remi.noarch
  register: rpm_check
  failed_when: no
  changed_when: no
  ignore_warnings: yes

- name: Download RedHat remi-release-7
  get_url:
    url: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    dest: /tmp/remi-release-7.rpm
    mode: 0775
  when: rpm_check.rc == 1

- name: Install RedHat remi-release-7
  command: rpm -Uvh /tmp/remi-release-7.rpm
  when: (ansible_os_family == 'RedHat') and rpm_check.stdout.find('is not installed') != -1
  changed_when: False
  become: yes

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: (php_install_from_source == false) and (ansible_os_family == 'RedHat')

- include_tasks: setup-Debian.yml
  when: (php_install_from_source == false) and (ansible_os_family == 'Debian')

# Install PHP from source when php_install_from_source is true.
- include_tasks: install-from-source.yml
  when: php_install_from_source == true

# Configure PHP.
- include_tasks: configure.yml
- include_tasks: configure-apcu.yml
- include_tasks: configure-opcache.yml
- include_tasks: configure-fpm.yml
