---

- name: Download Node.js 8.x LTS Carbon repo.
  get_url:
    url: "https://rpm.nodesource.com/setup_8.x"
    dest: "/root/nodejs_setup_8.x"

- name: Install Node.js 8.x LTS Carbon repo
  command: >
    bash /root/nodejs_setup_8.x

- name: Install Node.js 8.x LTS Carbon
  yum:
    name: nodejs
    state: latest
